sudo: false
env:
  global:
      - CXX=g++-9 CC=gcc-9
      - secure: gB/utRWujHAhKC97U3zlLweMQ69FvE/0TeWTI5MuPNHyDzE0RuHAJllia+k5TsVaR0+IzCGCJ2wPUphJl3dbdaJXuxO3sde2pYHsWyFSOnBQzUfHhQRvAn1SzPpVLRZ5j+lRXRmBCADBQPIiBa0VxpP5hlHU+kprRaY99y9jRbi4SB3FIYzCxaUPnaIfSlt+bs/DlPuy3rV04Kh1HNTyW/0hJhrvn/bycduDRGIyqVDG76zypxs+6AX1T8of//lU/WLJV5xuEycsphxH8AkBFkxNS1MYfrhsYQ3yc351Gw5ZlVPoD/FDZdHFZ4jJ9CQ6hQFSNDfSocPTUJVwkazunYaaqjy31il5CKBzKKbBhq6KoLGCCruV2FkTaglJP9SlbwoQN4S/EJ1e0slBeFaC5KdBz/eWINVrJ+MD3j9u57FPd4Lo5x0R/GtT0I779vWDRgWakB3WqmZjFROyAtHEWtAOf5/ctlSJKKrIsnJ5lWLZShx4rZnxRT6NC8NRzw0Lo6RUW1Gh6MIV2w5S+2SGe1EZRdXimJFPQXxoeZuKMpYzWbVd2ogTnAZcVU3oix4Jhu4r6aqVt9r4TEfAgO5DrP49X3wi4v2x/80xBn4QqZmHWGrI+Q7ErgDjvhFRxpfMe+OGxd1URXGQC2hhQPh179opDbE+2Aw1MQGCMPAYASQ=
notifications:
    email:
        on_success: never
script: ./travis.sh
dist: xenial
deploy:
    provider: releases
    # `api_key` is an encrypted oauth token for rafecolton. See https://docs.travis-ci.com/user/deployment/releases
    api_key:
        secure: jW0XqsVQ7TH3qtgPoDIV6YbcH0RITL/oAnCNXhUHnlr2f4vstIN7Izpef4MTrGFf6QszlEYmSVKGtpNbpiH+KpVqc8UTW1oGjh5b3FHShGvLggwe1GtApVyN21tW9jsScTNjs3nu2kXjPSz9UfLSNi/seRhSH8+TqStG3B31ItyJQmhs4YOX+uCKQLHxCjQMeAUz7BHhvWWfmd80gmjioX9D8hXfKIPTVDgBRlC0asnSXuILicM6TSFDDhtCIvKHnH7MIF/M+0J76OYPIeSK6KkYjCDMO1Ik9E6V7eDWCFIDq5zKarOuMktOKZ9KzMEDWKK+3zxVg4VjMyHTPDJeKaDzRRcyx2Dlk1fSX3gRJfcrbTeg3lrBwdlLbYMNo3Y2sJYhIp0sn4ZTDTSmrD25qVIg3pRaXj1PSZju5PU8SZN8b1xFyPFJJPhADSuD2gQTU88hBFA12d1/2UElStDt3UnyQlTZSmm8DeJ3HtDuQ3W2e4E64fzeXDW85SxBx3ecdSL5J0gBhQIcoHg6FuxTmXOOB71nTYmJb8OVZzVlFYiWIkIm0FlPTY8QGqUXhbScp4D/mLqTWlnllLsTcVKCe8lwzRBpFMkfbLWQy4EAvqjpAAmcWxHfTH39ORrO/J5ipZX+LQAAPwF8qDoedBYsZhUf4Duj1c/U++PNbF3mDM4=
    file:
        - bedrock
    skip_cleanup: true
    prerelease: true
    on:
        tags: true
